services:
    avatar.driver.gravatar:
        class: threedi\steamsuite\avatar\driver\gravatar
        arguments:
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@path_helper'
            - '@cache.driver'
        calls:
            - [set_name, [avatar.driver.gravatar]]
        tags:
            - { name: avatar.driver }

